version: '3.7'
services:
  wages-access-transaction-processor-api:
    image: wages-access-transaction-processor-api:latest
    env_file:
      - docker.local.env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        SERVER_PORT_LISTENING: ${SERVER_PORT_LISTENING}
        NODE_ENV: ${NODE_ENV}
        CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
        HOST_DB_CONFIG: ${HOST_DB_CONFIG}
        PORT_DB_CONFIG: ${PORT_DB_CONFIG}
        DIALECT_DB_CONFIG: ${DIALECT_DB_CONFIG}
        PROTOCOL_DB_CONFIG: ${PROTOCOL_DB_CONFIG}
        DATABASE_NAME_DB_CONFIG: ${DATABASE_NAME_DB_CONFIG}
        LOG_DEBUG_DB_CONFIG: ${LOG_DEBUG_DB_CONFIG}
        USER_NAME_DB_CONFIG: ${USER_NAME_DB_CONFIG}
        USER_PASSWORD_DB_CONFIG: ${USER_PASSWORD_DB_CONFIG}
    restart: always
    ports:
      - '6030:6030'
    volumes:
      - ./wages-access-transaction-processor-api-data:/wages-access-transaction-processor-api
    depends_on:
      - wages-access-transaction-processor-postgres
    networks:
      - wages-network

  wages-access-transaction-processor-postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wages-processor
    ports:
      - '5432:5432'
    volumes:
      - ./wages-access-transaction-processor-api-postgres-data:/var/lib/postgresql/data
    networks:
      - wages-network

networks:
  wages-network:
